config/routes.rb
Rails.application.routes.draw do
  get 'gossip/:gossip', to: 'unstatic_pages#gossip'
  get 'welcome/:first_name', to: 'welcome#show'
  get 'static_pages/contact', to: 'static_pages#contact'
  get 'static_pages/team', to: 'static_pages#team'
  get 'static_pages/index', to: 'static_pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :join_table_gossip_tags
  has_many :tags, through: :join_table_gossip_tags
end

app/models/join_table_gossip_tag.rb
class JoinTableGossipTag < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :gossips
  has_many :join_table_gossip_tags
  has_many :gossips, through: :join_table_gossip_tags
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city
  has_many :gossips
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def team
  end
  def contact
  end
  def index
    @gossips = Gossip.all
  end
end

app/controllers/unstatic_pages_controller.rb
class UnstaticPagesController < ApplicationController
  def gossip
    puts params[:title]
    @gossip = Gossip.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def show
    @first_name = params[:first_name]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/unstatic_pages_helper.rb
module UnstaticPagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header>
      <nav class="navbar navbar-expand-lg navbar-light bg-dark">
        <a class="navbar-brand text-light" href="#">The Gossip Project</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item active">
              <a class="nav-link text-light" <%= link_to "Accueil", static_pages_index_path%> <span class="sr-only">(current)</span> </a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-secondary" <%= link_to "Team", static_pages_team_path%> </a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-secondary" <%= link_to "Contact", static_pages_contact_path%> </a>
            </li>
            
            <!--
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle text-secondary" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Nos prochaines sessions
              </a>
            </li>
            -->
          </ul>
        </div>
      </nav>
    </header>

    <%= yield %>

  </body>
</html>

app/views/static_pages/contact.html.erb
<h1>Vous souhaitez nous contacter ? Nous, non, pas le temps désolé :(</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/index.html.erb
<h1>Bienvenue !</h1>

<p> Salut ! Ici c'est notre super site de potins, il est chouette, non ? </p>

 <% @gossips.each do |gossip| %>
    <p>
      Le nom de l'auteur : <%= gossip.user.first_name %><br/>
      Le titre du gossip : <%= gossip.title %> <br/>
      </p>

      <%= link_to "Lire", ("/gossip/#{gossip.id}") %>
<% end %>

app/views/static_pages/team.html.erb
<h1>Ceci est la page de notre équipe. Découvrez ces affreux :</h1>

app/views/unstatic_pages/gossip.html.erb
<h1>Ceci est la page du gossip N° <%= gossip</h1>
<p>Find me in app/views/unstatic_pages/gossip.html.erb</p>

app/views/welcome/show.html.erb
<h1>Bienvenue !</h1>

<p> Salut <%= @first_name %> ! Ici c'est notre super site de potins, il est chouette, non ? </p>